openapi: 3.0.2
info:
  version: 1.0.0
  title: vinterapi.com
  termsOfService: 'https://vinterapi.com/terms/'
  contact:
    email: contact@vinter.capital
    url: 'https://vintercapital.com/contact'
    name: Hakan Holmberg
  license:
    name: 'Proprietary '
    url: www.vinter.capital
  x-logo:
    url: 'https://images.squarespace-cdn.com/content/5d1c6b091629cd0001317c9e/1562720287537-1UD7556IUOWTYP94X3QL/vintercaptranspa.png?format=1500w&content-type=image%2Fpng'
  description: |
    # Introduction
    This API definition describes Vinter Capital's API enpoints.
tags:
  - name: Vinter Mid Index
    description: The vinter mid index endpoint
  - name: Vinter Reference Index
    description: The vinter reference index endpoint
  - name: Vinter Realtime Index
    description: The vinter realtime index endpoint
servers:
  - url: 'https://vinterapi.com/api/v1'
paths:
  /realtime_index/:
    $ref: paths/realtime_index.yaml
  /reference_index/:
    $ref: paths/reference_index.yaml
  /vinter_mid_index/:
    $ref: paths/vinter_mid_index.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
  schemas: {}
