openapi: 3.0.2
info:
  version: 1.0.0
  title: The Vinter APIs
  termsOfService: 'https://vinterapi.com/terms/'
  contact:
    email: contact@vinter.capital
    url: 'https://vintercapital.com/contact'
    name: contact
  license:
    name: 'Proprietary '
    url: www.vinter.capital
  x-logo:
    url: 'https://res-2.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco/ewbs0jxslmtxft2ihras'
  description: |
    # Introduction
    "This API definition describes Vinter Capital's API enpoints. An API key is      required for all endpoints and can be requested by sending a e-mail to          contact@vinter.capital. The API key should be placed in the headers             authorization field.
      ```
      Authorization:: Api-Key ********
      ```
      "
tags:
  - name: Vinter Universe
    description: Information on eligible exchanges and constituents
  - name: Vinter Reference Index
    description: The vinter reference index endpoint
  - name: Vinter Realtime Index
    description: The vinter realtime index endpoint 
servers:
  - url: 'https://vinterapi.com/api/v1'
paths:
  /realtime_index/:
    $ref: paths/realtime_index.yaml
  /reference_index/:
    $ref: paths/reference_index.yaml
  /vinter_universe/:
    $ref: paths/vinter_universe.yaml
# components:
#  securitySchemes:
#    Api-Key:
#      type: apiKey
#      in: header
#      name: Api-Key
#  schemas: {}
#security:
#  - ApiKeyAuth: []
