openapi: 3.0.2
info:
  version: 1.0.0
  title: vinterapi.com
  termsOfService: 'https://vinterapi.com/terms/'
  contact:
    email: contact@vinter.capital
    url: 'https://vintercapital.com/contact'
    name: Hakan Holmberg
  license:
    name: 'Proprietary '
    url: www.vinter.capital
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description: |
    # Introduction
    This API definition describesVinter Capital's API enpoints.
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Echo
    description: Example echo operations
  - name: User
    description: Operations about user
servers:
  - url: 'https://vinterapi.com/api/v1'
paths:
  '/users/{username}':
    $ref: 'paths/users@{username}.yaml'
  /echo:
    $ref: paths/echo.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
